export const metadata = {
  title: "Projects | Hezekiah Elisha",
  keywords: [
    "Hezekiah Elisha",
    "Portfolio",
    "Web Developer",
    "Software Engineer",
    "Next.js",
    "React",
    "JavaScript",
  ],
  authors: [
    {
      name: "Hezekiah Elisha",
      url: "https://hezekiahelisha.com",
    },
  ],
  creator: "Hezekiah Elisha",
  description: "Generated by create next app",
};

export default function ProjectsLayout({ children }) {
  return children;
}
