import Header from "@/components/Header";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata = {
  title: "Hezekiah Elisha",
  keywords: [
    "Hezekiah Elisha",
    "Portfolio",
    "Web Developer",
    "Software Engineer",
    "Next.js",
    "React",
    "JavaScript",
  ],
  authors: [
    {
      name: "Hezekiah Elisha",
      url: "https://hezekiahelisha.com",
    },
  ],
  creator: "Hezekiah Elisha",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`antialiased`} suppressHydrationWarning>
      <body className="w-screen h-screen bg-gradient-to-r from-secondary/95 via-secondary/90 to-secondary/85">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
